# version: '3.9'


services:

  info-search-app-db:
    container_name: info-search-app-db
    image: postgres:13.7-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

  info-search-app:
    container_name: info-search-app
    build:
      context: .
      network: host
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
